name: Docker

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    uses: "mostpinkest/workflows/.github/workflows/docker.yml@main"
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    with:
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  dockerhub-description:
    uses: "mostpinkest/workflows/.github/workflows/dockerhub-description.yml@main"
    needs:
      - publish
    permissions:
      contents: read
    with:
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
